/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  period?: string;
  title?: string;
  institution?: string;
  description?: Array<string>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  title?: string;
  description?: string;
  img?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  liveLink?: string;
  gitHubLink?: string;
  iconLists?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type GridItem = {
  _id: string;
  _type: "gridItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  title?: string;
  description?: string;
  img?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  spareImg?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  techStackLeft?: Array<string>;
  techStackRight?: Array<string>;
  isContactCard?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Education
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | GridItem
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: sanity/lib/sanity.queries.ts
// Variable: BENTO_GRID_QUERY
// Query: *[_type == "gridItem"] | order(id asc) {  id,  title,  description,  "img": img.asset->url,  "spareImg": spareImg.asset->url,  techStackLeft,  techStackRight,  isContactCard}
export type BENTO_GRID_QUERY_RESULT = Array<{
  id: number | null;
  title: string | null;
  description: string | null;
  img: string | null;
  spareImg: string | null;
  techStackLeft: Array<string> | null;
  techStackRight: Array<string> | null;
  isContactCard: boolean | null;
}>;

// Source: sanity/lib/sanity.queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(id asc) {  id,  title,  description,  "img": img.asset->url,  liveLink,  gitHubLink,  iconLists}
export type PROJECTS_QUERY_RESULT = Array<{
  id: number | null;
  title: string | null;
  description: string | null;
  img: string | null;
  liveLink: string | null;
  gitHubLink: string | null;
  iconLists: Array<string> | null;
}>;

// Source: sanity/lib/sanity.queries.ts
// Variable: EDUCATION_QUERY
// Query: *[_type == "education"] | order(id asc) {  id,  period,  title,  institution,  description}
export type EDUCATION_QUERY_RESULT = Array<{
  id: number | null;
  period: string | null;
  title: string | null;
  institution: string | null;
  description: Array<string> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "gridItem"] | order(id asc) {\n  id,\n  title,\n  description,\n  "img": img.asset->url,\n  "spareImg": spareImg.asset->url,\n  techStackLeft,\n  techStackRight,\n  isContactCard\n}': BENTO_GRID_QUERY_RESULT;
    '*[_type == "project"] | order(id asc) {\n  id,\n  title,\n  description,\n  "img": img.asset->url,\n  liveLink,\n  gitHubLink,\n  iconLists\n}': PROJECTS_QUERY_RESULT;
    '*[_type == "education"] | order(id asc) {\n  id,\n  period,\n  title,\n  institution,\n  description\n}': EDUCATION_QUERY_RESULT;
  }
}
